package com.sxw.sxwaiagent.hermes;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Hermes candidate item.
 * <p>
 * Improvement candidates generated by the Hermes analyzer, requiring user review before application.
 * This is the core data model of the Hermes review system.
 */
public record HermesCandidate(
    Long id,
    String candidateId,
    String sourceRequestId,
    String sourceTraceId,
    HermesCandidateType candidateType,
    String title,
    String content,
    String targetStore,
    BigDecimal confidence,
    HermesCandidateStatus status,
    LocalDateTime createdAt,
    LocalDateTime reviewedAt,
    String reviewedBy,
    LocalDateTime appliedAt,
    String applyResult
) {
    /**
     * Convenience constructor: create candidate in PENDING status.
     */
    public HermesCandidate(
        String candidateId,
        String sourceRequestId,
        String sourceTraceId,
        HermesCandidateType candidateType,
        String title,
        String content,
        String targetStore,
        BigDecimal confidence
    ) {
        this(null, candidateId, sourceRequestId, sourceTraceId, candidateType,
            title, content, targetStore, confidence,
            HermesCandidateStatus.PENDING, LocalDateTime.now(),
            null, null, null, null);
    }

    /**
     * Check if candidate can be applied.
     */
    public boolean canApply() {
        return status == HermesCandidateStatus.APPROVED;
    }

    /**
     * Check if candidate can be reviewed.
     */
    public boolean canReview() {
        return status == HermesCandidateStatus.PENDING;
    }

    /**
     * Check if high confidence (can be auto-approved).
     */
    public boolean isHighConfidence() {
        return confidence != null && confidence.compareTo(new BigDecimal("0.9")) >= 0;
    }

    /**
     * Build summary text.
     */
    public String buildSummary() {
        return String.format("[%s] %s (%s) - confidence=%.2f, status=%s",
            candidateId, title, candidateType,
            confidence != null ? confidence : BigDecimal.ZERO,
            status);
    }
}
